# Generated by Django 4.1.7 on 2023-04-15 08:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("APP1", "0003_user_avater"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bought_goods",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("c_time", models.DateTimeField(auto_created=True)),
                ("state", models.PositiveSmallIntegerField(default=0)),
                ("uid", models.IntegerField()),
                ("sid", models.IntegerField()),
                ("quantity", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Goods",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("c_time", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=50)),
                ("level", models.SmallIntegerField(blank=True)),
                ("remark", models.CharField(blank=True, max_length=255)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("sort", models.PositiveSmallIntegerField()),
                ("count", models.PositiveSmallIntegerField()),
                ("display", models.BooleanField(default=False)),
                ("transaction", models.PositiveSmallIntegerField()),
                ("sales", models.PositiveSmallIntegerField(default=0)),
                ("uid", models.IntegerField()),
                ("image", models.ImageField(max_length=255, upload_to="img")),
            ],
        ),
        migrations.CreateModel(
            name="Goods_message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("c_time", models.DateTimeField(auto_now_add=True)),
                ("sid", models.IntegerField()),
                ("content", models.CharField(max_length=128)),
                ("display", models.BooleanField(default=True)),
                ("uid", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Passwrd",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("c_time", models.DateTimeField(auto_now_add=True)),
                ("password", models.CharField(max_length=255)),
                ("uid", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Post_goods",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("c_time", models.DateTimeField(auto_now_add=True)),
                ("displa", models.BooleanField(default=False)),
                ("uid", models.IntegerField()),
                ("sid", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Shopping_cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("c_time", models.DateTimeField(auto_now_add=True)),
                ("display", models.BooleanField()),
                ("uid", models.IntegerField()),
                ("sid", models.IntegerField()),
                ("quantity", models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name="user",
            name="password",
        ),
        migrations.AddField(
            model_name="user",
            name="message",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="user",
            name="avater",
            field=models.ImageField(max_length=255, upload_to="img"),
        ),
    ]
