# Generated by Django 4.1.7 on 2023-04-15 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("APP1", "0004_bought_goods_goods_goods_message_passwrd_post_goods_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="passwrd",
            name="uid",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="APP1.user"
            ),
        ),
    ]
