# Generated by Django 4.1.7 on 2023-04-15 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("APP1", "0006_alter_user_avater_alter_user_message"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="passwrd",
            name="id",
        ),
        migrations.AlterField(
            model_name="passwrd",
            name="uid",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to="APP1.user",
            ),
        ),
    ]
