# Generated by Django 4.1.7 on 2023-04-15 11:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("APP1", "0007_remove_passwrd_id_alter_passwrd_uid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="passwrd",
            name="uid",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
