# Generated by Django 4.1.7 on 2023-04-15 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("APP1", "0009_alter_passwrd_uid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="passwrd",
            name="uid",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to="APP1.user",
            ),
        ),
    ]
