# Generated by Django 4.1.7 on 2023-04-25 11:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("APP1", "0010_alter_passwrd_uid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goods",
            name="transaction",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
